### PR TITLE
Launcher icon are built by taking a one density bucket higher icon.

### PR DESCRIPTION
**Pull request by MaTriXy**
Also, Launcher icons should be placed on mipmap folder according to density.
All the rest is ok.

### CODE REVIEW

**Comment by tomerlevi444** [comment]
Is it backwards compatible with API LEVEL 14 ?

**Comment by MaTriXy** [comment]
By placing your launcher icon in the mipmap-xhdpi directory, it will not be stripped the way a drawable-xhdpi directory is when building an APK for hdpi devices. 
Supported on API 14

**Comment by tomerlevi444** [comment]
Why is it exactly the same png file in all mipmap directories?

**Comment by MaTriXy** [comment]
I had only one size icon launcher - but in practice you should have several sizes.
http://developer.android.com/design/style/iconography.html

**Pull request closed without merging**
